version: '3.8'
services:

  posts-db:
    image: postgres:15.1-alpine
    container_name: posts-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    restart: unless-stopped

  votes-db:
    image: postgres:15.1-alpine
    container_name: votes-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "25432:5432"
    restart: unless-stopped
